version: "3"

services:
  # namenode:
  #   image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
  #   container_name: namenode
  #   restart: always
  #   ports:
  #     - 9870:9870
  #     - 9010:9000
  #   volumes:
  #     - hadoop_namenode:/hadoop/dfs/name
  #     - ../data:/mnt
  #   environment:
  #     - CLUSTER_NAME=namenode
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
  #   env_file:
  #     - ./hadoop.env

  datanode_1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode_1
    restart: always
    volumes:
      - hadoop_datanode_1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "http://192.168.0.160:9870"
      CORE_CONF_fs_defaultFS: hdfs://192.168.0.160:9000
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop.env
      
  # datanode_2:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: datanode_2
  #   restart: always
  #   volumes:
  #     - hadoop_datanode_2:/hadoop/dfs/data
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870"
  #     CORE_CONF_fs_defaultFS: hdfs://namenode:9000
  #   ports:
  #     - "9865:9865"
  #   env_file:
  #     - ./hadoop.env
      
  # datanode_3:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: datanode_3
  #   restart: always
  #   volumes:
  #     - hadoop_datanode_3:/hadoop/dfs/data
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870"
  #     CORE_CONF_fs_defaultFS: hdfs://namenode:9000
  #   ports:
  #     - "9866:9866"
  #   env_file:
  #     - ./hadoop.env

  # resourcemanager:
  #   image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
  #   container_name: resourcemanager
  #   restart: always
  #   environment:
  #     # SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode_1:9864 datanode_2:9865 datanode_3:9866"
  #     SERVICE_PRECONDITION: "namenode:9000 namenode:9870"
  #   env_file:
  #     - ./hadoop.env

  # nodemanager1:
  #   image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
  #   container_name: nodemanager
  #   restart: always
  #   environment:
  #     # SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode_1:9864 datanode_2:9865 datanode_3:9866"
  #     SERVICE_PRECONDITION: "namenode:9000 namenode:9870"
  #   env_file:
  #     - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      # SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode_1:9864 datanode_2:9865 datanode_3:9866"
      SERVICE_PRECONDITION: "datanode_1:9864"    
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  # hive-server:
  #   image: bde2020/hive:2.3.2-postgresql-metastore
  #   container_name: hive-server
  #   depends_on:
  #     - namenode
  #     # - datanode_1
  #     # - datanode_2
  #     # - datanode_3
  #   env_file:
  #     - ./hadoop-hive.env
  #   environment:
  #     HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
  #     SERVICE_PRECONDITION: "hive-metastore:9083"
  #   ports:
  #     - "10000:10000"

volumes:
  # hadoop_namenode:
  hadoop_datanode_1:
  # hadoop_datanode_2:
  # hadoop_datanode_3:
  hadoop_historyserver:

